### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by KonradIT** [KonradIT/gopro_fw_dl#1]
- [x] add HERO3 cameras
- [ ] make cron job that alerts you when a new firmware is available
- [x] add python2 support
- [x] add arguments: gopro-fw-dl.py [camera_model]
- [x] direct unzip to SD card if SD card is mounted
